# Generated by Django 3.2.15 on 2023-08-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_profileimg_profile_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='profileimg',
        ),
    ]
